Android.mk: Put qmcs image behind sm8350 platform filter
sonyxperiadev/vendor-qcom-opensource-display pull request #2
Opened 2022-02-04 15:15 UTC by Haxk20

qmcs is a new Display partition that has been added in Lahaima SoC (Sagami platform for us).

Thus we do not need to generate this image for other platforms as it serves no purpose.

Source: [40afb6f4f07e5036a8547765f8352775128614dc](https://github.com/sonyxperiadev/vendor-qcom-opensource-display/commit/40afb6f4f07e5036a8547765f8352775128614dc)

2022-02-04 15:16 UTC, Haxk20 commented
Tested on Edo build. No qmcs image is generated.

2022-02-04 15:27 UTC, bartcubbins approved these changes

2022-02-04 15:28 UTC, MarijnS95 requested changes
What's `Lahaima`

2022-02-04 15:43 UTC, Haxk20 commented
> What's `Lahaima`

👀 I will fix the typo later today :P

2022-02-07 08:43 UTC, jerpelea commented
we do not use this partition ! you can exclude it for all devices

2022-02-07 08:58 UTC, closed without merging